# This option allows you to set where
# player's data do you want to save.
# 
# Storages: 'file' or 'mysql'.
# 
# If you enable mysql, you need to setup MySQL infos.
Player-Data:
  Storage: file
  MySQL:
    hostname: localhost
    username: root
    database: minecraft
    port: '3306'
    password: password
Cosmetic-Item-Purchase:
  # Set to true allows player to purchase cosmetic items.
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'file', 'mysql', 'coins-jasperjh', 'coinsapi', 'playerpoints', 'vault'.
  Mystery-Dust-Storage: file
  # Set to true will allows player to purchase specified cosmetic.
  Enabled-Cosmetics:
    Hats: true
    Animated Hats: true
    Particles: true
    Suits: true
    Gadgets: true
    Pets: true
    Miniatures: true
    Morphs: true
    Banners: true
    Emotes: true
    Cloaks: true
  # Reopen GUI menu after player purchase item.
  Reopen-GUI-Menu-After-Purchase: true
# General settings.
Settings:
  # The default pet's name.
  Default-Pet-Name: '&cZwierzak {PLAYER}'
  # The mystery dust amount of the player who join the server first time.
  Starting-Mystery-Dust: 0
  # The maximum characters that player can set the pet name.
  Max-Pet-Name-Characters: 20
  # The slot when player equip gadget, emote or morph.
  Gadget-Slot: 5
  # The default value of Mystery Vault animation.
  # The value of the player who join the server first time.
  Default-Mystery-Vault-Animation: NORMAL
  # The default self morph view setting.
  Default-Self-Morph-View: true
  # Do you want to enable self morph view?
  Enabled-Self-Morph-View: true
  # Do you want to enable mob disguise damage?
  # Set to false will disable damage if disguised.
  Enabled-Mob-Disguise-Damage: false
  # Auto equip cosmetic after player purchased.
  Auto-Equip-After-Purchase: true
  # Auto equip cosmetic when player found loot from mystery box.
  Auto-Equip-On-Loot-Found: true
  # Set to true will shows particle effect to everyone,
  # otherwise will only show to the player itself.
  Show-Particle-Effect-To-Everyone: true
  # Set to true will shows cloak effect to everyone,
  # otherwise will only show to the player itself.
  Show-Cloak-Effect-To-Everyone: true
  # Set to true will hide particle effect for vanished player.
  Hide-Particle-Effect-For-Vanished-Player: true
  # Set to true will hide cloak effect for vanished player.
  Hide-Cloak-Effect-For-Vanished-Player: true
  # Do action when player equip cosmetic.
  # Replace: Replace the old item with equipped cosmetic.
  # Warn: Send a warning message to the player and reject to equip cosmetic.
  # Drop: Drop the old item on the ground and equip cosmetic.
  Equip-Cosmetic-Item-To-Slot: WARN
  # Sync player's selected cosmetics when they join the server.
  # Set to 'false' to reduce server lag.
  Sync-Cosmetics-On-Join: true
# The menu selector settings.
Menu-Item:
  # The name of the selector.
  Name: '&aGadzety'
  # The material of the selector.
  # Material: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Material-Syntax
  Material: NETHER_STAR
  # Slot: 0-8
  Slot: 4
  # Should give player menu selector when they join the server.
  Give-On-Join: true
  # Should give player menu selector when they switch between the worlds.
  Give-On-Change-World: true
  # Set to true allows player to move menu selector to another slot.
  Able-To-Move: false
  Lore:
  - '&7Tajemniczy Pyl: &a{MYSTERY_DUST}'
  - ''
  - '&7W pelni kosmetyczne dodatki!'
  - '&7Zdobywaj wiecej otwierajac,'
  - '&7tajemnicze pudelka na lobby!'
  - '&7Graj na serwerze aby je zdobyc.'
# List of the worlds where cosmetics are enabled!
Enabled-Worlds:
- world
- world_nether
- world_the_end
# List of the disabled cosmetics.
# Set to true to disable it.
Disabled-Cosmetics:
  Hats: false
  Animated Hats: false
  Particles: false
  Suits: false
  Gadgets: false
  Pets: false
  Miniatures: true
  Morphs: false
  Banners: false
  Emotes: false
  Cloaks: false
# Sync the last equipped cosmetics when player join the server.
Cosmetics-Sync-On-Join:
  Hats: true
  Animated Hats: true
  Particles: true
  Suits: true
  Gadgets: true
  Pets: true
  Miniatures: true
  Morphs: true
  Banners: true
  Emotes: true
  Cloaks: true
Permission:
  # When player doesn't have the permission of that item.
  No-Permission:
    # Set to true will show the lore.
    Show-In-Lore: false
    # Should close GUI menu when player selected 
    # a item which he doesn't have the permission.
    Close-GUI-Menu-After-Select: true
    Lore:
    - ''
    - '&7Status: &c&lZABLOKOWANE'
    # Set to true, will play sound 
    # when player select the item.
    # 
    # Sounds: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Sounds
    Play-Sound:
      Enabled: true
      Sound: ENTITY_ENDERMAN_TELEPORT
    Show-Custom-Item:
      Enabled: true
      Material: GRAY_DYE
  # When player have the permission of that item.
  Has-Permission:
    # Set to true will show the lore.
    Show-In-Lore: false
    Close-GUI-Menu-After-Select: true
    Lore:
    - ''
    - '&7Status: &a&lODBLOKOWANE'
    # Set to true, will play sound 
    # when player select the item.
    # 
    # Sounds: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Sounds
    Play-Sound:
      Enabled: true
      Sound: ENTITY_EXPERIENCE_ORB_PICKUP
# Discount the cost of an item when player purchase.
Item-Cost-Discount:
  # Set to true will enable item cost discount.
  Enabled: false
  # Which item do you want to enable item cost discount?
  Discount:
    Cosmetic-Item: false
    Crafting-Mystery-Box: true
  # You can add more discount rate by reference example.
  Discount-Rates:
    # The name of the discount group.
    # The name is use for placeholder to get the cost after discount.
    # Placeholder Syntax: {<name>_MYSTERY_DUST}
    # Get the cost of that discount rate.
    Default:
      # Higher numbers override.
      Priority: 1
      # The permission to granted discount.
      Permission: gadgetsmenu.discount.default
      # Discount rates.
      Rate: 0
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&aRegular&7: &a{MYSTERY_DUST} &7Mystery Dust! &e◀'
        - '&cVIP: {VIP_MYSTERY_DUST} Mystery Dust (&a20% &7OFF!)'
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &a{MYSTERY_DUST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust! &e◀'
        - '&cVIP: {VIP_MYSTERY_DUST} Mystery Dust (&a20% &7OFF!)'
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &c{MYSTERY_DUST} &7Mystery Dust'
        - '&cYou need &b{SURPLUS_MYSTERY_DUST} &cmore mystery dust!'
    # The name of the discount group.
    # The name is use for placeholder to get the cost after discount.
    # Placeholder Syntax: {<name>_MYSTERY_DUST}
    # Get the cost of that discount rate.
    VIP:
      # Higher numbers override.
      Priority: 2
      # The permission to granted discount.
      Permission: gadgetsmenu.discount.VIP
      # Discount rates.
      Rate: 20
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&aVIP&7: &a{VIP_MYSTERY_DUST} &7Mystery Dust (&a20% &7OFF!) &e◀'
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &a{VIP_MYSTERY_DUST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&aVIP&7: &a{VIP_MYSTERY_DUST} &7Mystery Dust (&a20% &7OFF!) &e◀'
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &c{VIP_MYSTERY_DUST} &7Mystery Dust'
        - '&cYou need &b{SURPLUS_MYSTERY_DUST} &cmore mystery dust!'
    MVP:
      Priority: 3
      Permission: gadgetsmenu.discount.MVP
      Rate: 40
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&8&mVIP: {VIP_MYSTERY_DUST} Mystery Dust (20% OFF!)'
        - '&bMVP&7: &a{MVP_MYSTERY_DUST} &7Mystery Dust (&a40% &7OFF!) &e◀'
        - ''
        - '&7Your Cost: &a{MVP_MYSTERY_DUST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&8&mVIP: {VIP_MYSTERY_DUST} Mystery Dust (20% OFF!)'
        - '&bMVP&7: &a{MVP_MYSTERY_DUST} &7Mystery Dust (&a40% &7OFF!) &e◀'
        - ''
        - '&7Your Cost: &a{MVP_MYSTERY_DUST} &7Mystery Dust'
        - '&cYou need &b{SURPLUS_MYSTERY_DUST} &cmore mystery dust!'
# When player clicks 'Go Back' button will execute these commands.
# If you enabled this option, it won't open the main menu of GadgetsMenu.
# Variables: {PLAYER}
Back-To-Main-Menu:
  Execute-Commands:
    Enabled: false
    Commands:
    - cc open menu.yml {PLAYER}
# Set to true will fill the blank slots of inventories with the item you set.
Fill-Empty-Slot-With-Item:
  Enabled: false
  Material: BLACK_STAINED_GLASS_PANE
# List of commands that won't work when equip a cosmetic.
# Type commands in lowercase without slashes.
Disabled-Commands:
- hat
# Anti Lag System.
# Activate these actions if server TPS is below the minimum TPS.
Anti-Lag:
  Enabled: true
  Minimum-TPS: 17
  Action:
    # Unequip online players cosmetics.
    Clear-Cosmetics: true
    # Disable the usage of cosmetics.
    Disable-Usage: true
# Player does not allow to use cosmetics in these regions. (Required WorldGuard)
Blacklisted-Regions:
- region1
- region2
- region3
# Check for updates if you set to true.
Check-Update: false
# Set to true will automatic download 
# the latest plugin when it's released.
Auto-Update: false
# Do not edit this.
Config-Version: 1.0.14
